version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    #extra_hosts:
    #  - "db:localhost"
    environment:
      - MONGO_URI=mongodb://db:27017
    links:
      - db
  db:
    container_name: db
    build: ./db
    ports:
      - "27017:27017"
